"""T81 — licensing/subscription status and on-prem license management."""
import uuid
from fastapi import APIRouter, Depends, UploadFile, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession

from ...deps import get_tenant_db, require_permission
from ...schemas.auth import TokenPayload
from ...config import settings
from ...services import license_service

router = APIRouter()


@router.get('/billing/subscription')
async def get_subscription_status(
    current_user: TokenPayload = Depends(require_permission("billing.view")),
    db: AsyncSession = Depends(get_tenant_db),
):
    """SaaS mode: current plan, usage, and whether uploads are currently allowed."""
    tenant_id = uuid.UUID(current_user.tenant_id)
    result = await license_service.check_saas_capacity(db, tenant_id)
    await db.commit()  # persists a lazily-created trial subscription, if any
    return {
        "deployment_mode": settings.deployment_mode,
        "plan_key": result.plan_key,
        "plan_label": license_service.PLAN_DEFINITIONS.get(result.plan_key, {}).get("label"),
        "status": result.status,
        "upload_allowed": result.allowed,
        "blocked_reason": result.reason if not result.allowed else None,
        "documents_used": result.documents_used,
        "documents_limit": result.documents_limit,
        "storage_used_bytes": result.storage_used_bytes,
        "storage_limit_bytes": result.storage_limit_bytes,
        "trial_or_period_ends_at": result.expires_at.isoformat() if result.expires_at else None,
    }


@router.get('/billing/license')
async def get_license_status(
    current_user: TokenPayload = Depends(require_permission("license.manage")),
    db: AsyncSession = Depends(get_tenant_db),
):
    """On-prem mode: status of the currently-installed signed capacity license."""
    result = await license_service.check_onprem_capacity(db)
    lic = await license_service.get_installed_license(db)
    return {
        "deployment_mode": settings.deployment_mode,
        "status": result.status,
        "upload_allowed": result.allowed,
        "blocked_reason": result.reason if not result.allowed else None,
        "customer_name": lic.raw_payload.get("customer_name") if lic else None,
        "plan_key": lic.raw_payload.get("plan_key") if lic else None,
        "max_nodes": lic.raw_payload.get("max_nodes") if lic else None,
        "max_gpu_count": lic.raw_payload.get("max_gpu_count") if lic else None,
        "expires_at": lic.raw_payload.get("expires_at") if lic else None,
        "installed_at": lic.installed_at.isoformat() if lic else None,
        "is_valid": lic.is_valid if lic else False,
    }


@router.post('/billing/license')
async def install_license(
    file: UploadFile,
    current_user: TokenPayload = Depends(require_permission("license.manage")),
    db: AsyncSession = Depends(get_tenant_db),
):
    """Upload a signed .lic file generated by scripts/generate_license.py.
    Stored even if invalid, so a bad install attempt is visible in status
    rather than silently discarded — see license_service.install_license."""
    raw_bytes = await file.read()
    lic = await license_service.install_license(db, raw_bytes, uuid.UUID(current_user.sub))
    if not lic.is_valid:
        raise HTTPException(status_code=400, detail=f"License installed but is not currently valid: {lic.invalid_reason}")
    return {
        "installed": True,
        "customer_name": lic.raw_payload.get("customer_name"),
        "expires_at": lic.raw_payload.get("expires_at"),
    }
