"""T81 — licensing enforcement.

Two independent mechanisms, picked by settings.deployment_mode:

- SaaS: usage (document count, storage bytes) is metered live against a
  subscription plan. See PLAN_DEFINITIONS below for the plan limits —
  every number is a placeholder pending real business sign-off (A5), not
  a decided price sheet. See docs/decisions/T81_licensing_assumptions.md
  for the full list.

- On-prem/air-gapped: cannot phone home to check a subscription without
  breaking T92's egress-zero guarantee, so capacity is instead granted by
  a signed license file, verified offline via Ed25519 (no network call).
  Generated by backend/scripts/generate_license.py, which holds the
  private key — this module only ever sees the public key, so a leaked
  deployment can't forge its own license.

Both mechanisms fail OPEN on breach, not closed: over-limit or
expired/missing/invalid blocks new document uploads (the metered action)
but never blocks reading, searching, or exporting data already ingested.
This is deliberate for an evidence system — locking a customer out of
their own legal records over a billing lapse is a worse outcome than a
grace period. Missing/invalid on-prem licenses get a
settings.license_grace_period_days grace window before the block kicks
in, mirroring how SaaS trial expiry behaves.
"""
import base64
import json
import logging
from dataclasses import dataclass
from datetime import datetime, timedelta
from typing import Optional
from uuid import UUID

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import settings
from app.models.subscription import Subscription
from app.models.license import License
from app.models.document import Document
from app.models.document_version import DocumentVersion

logger = logging.getLogger(__name__)

# Placeholder tiers — see docs/decisions/T81_licensing_assumptions.md. max_documents/
# max_storage_bytes are None for "unlimited". trial_days only applies to
# the 'trial' plan.
PLAN_DEFINITIONS = {
    "trial": {"label": "Trial", "max_documents": 100, "max_storage_bytes": 2 * 1024**3, "trial_days": 30},
    "starter": {"label": "Starter", "max_documents": 2_000, "max_storage_bytes": 50 * 1024**3},
    "professional": {"label": "Professional", "max_documents": 20_000, "max_storage_bytes": 500 * 1024**3},
    "enterprise": {"label": "Enterprise", "max_documents": None, "max_storage_bytes": None},
}

# Public half of the offline signing keypair generate_license.py signs
# with. Rotating this requires re-issuing every outstanding license.
# DEV-ONLY keypair, generated for this scaffold — see
# docs/decisions/T81_licensing_assumptions.md. Before any real deployment, regenerate the
# pair and keep the private half out of version control entirely (a
# secrets vault, not this repo) — its value here only exists so the
# feature can be exercised end-to-end in dev.
VENDOR_PUBLIC_KEY_B64 = "t/vOW8cFyjWFWJ6GhCNGowAdea50rws21+3/RrfLyDI="


@dataclass
class LicenseCheckResult:
    allowed: bool
    reason: Optional[str]
    status: str  # trialing | active | expired | grace | blocked
    plan_key: Optional[str] = None
    documents_used: Optional[int] = None
    documents_limit: Optional[int] = None
    storage_used_bytes: Optional[int] = None
    storage_limit_bytes: Optional[int] = None
    expires_at: Optional[datetime] = None


def _canonical_payload_bytes(payload: dict) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")


def verify_license_signature(payload: dict, signature_b64: str) -> tuple[bool, Optional[str]]:
    """Ed25519 signature check, entirely offline — no network call, so this
    works identically in an air-gapped deployment. Returns (is_valid, reason)."""
    try:
        public_key = Ed25519PublicKey.from_public_bytes(base64.b64decode(VENDOR_PUBLIC_KEY_B64))
        signature = base64.b64decode(signature_b64)
        public_key.verify(signature, _canonical_payload_bytes(payload))
        return True, None
    except InvalidSignature:
        return False, "Signature does not match payload — the license file was altered or was not signed with the vendor key."
    except Exception as e:
        return False, f"Malformed license file: {e}"


async def get_or_create_subscription(db: AsyncSession, tenant_id: UUID) -> Subscription:
    """Lazily creates a trial subscription for any tenant that predates
    T81 or was otherwise created outside sign_up (e.g. test fixtures)."""
    sub = await db.get(Subscription, tenant_id)
    if sub:
        return sub
    plan = PLAN_DEFINITIONS["trial"]
    sub = Subscription(
        tenant_id=tenant_id,
        plan_key="trial",
        status="trialing",
        trial_ends_at=datetime.utcnow() + timedelta(days=plan["trial_days"]),
    )
    db.add(sub)
    await db.flush()
    return sub


async def _current_usage(db: AsyncSession, tenant_id: UUID) -> tuple[int, int]:
    """Computed live from Document/DocumentVersion rather than a counter
    column, so it can never drift from what's actually stored."""
    doc_count = (await db.execute(
        select(func.count(Document.id)).where(Document.tenant_id == tenant_id, Document.is_trashed == False)
    )).scalar() or 0
    storage_bytes = (await db.execute(
        select(func.coalesce(func.sum(DocumentVersion.file_size_bytes), 0))
        .join(Document, Document.current_version_id == DocumentVersion.id)
        .where(Document.tenant_id == tenant_id, Document.is_trashed == False)
    )).scalar() or 0
    return doc_count, storage_bytes


async def check_saas_capacity(db: AsyncSession, tenant_id: UUID) -> LicenseCheckResult:
    sub = await get_or_create_subscription(db, tenant_id)
    plan = PLAN_DEFINITIONS.get(sub.plan_key, PLAN_DEFINITIONS["trial"])
    doc_count, storage_bytes = await _current_usage(db, tenant_id)

    if sub.status == "trialing" and sub.trial_ends_at and datetime.utcnow() > sub.trial_ends_at:
        return LicenseCheckResult(
            allowed=False,
            reason=f"Trial expired on {sub.trial_ends_at.date().isoformat()}. Existing documents remain fully readable and exportable; upgrade to a paid plan to resume uploading.",
            status="expired",
            plan_key=sub.plan_key,
            documents_used=doc_count,
            documents_limit=plan["max_documents"],
            storage_used_bytes=storage_bytes,
            storage_limit_bytes=plan["max_storage_bytes"],
            expires_at=sub.trial_ends_at,
        )

    if sub.status in ("expired", "canceled"):
        return LicenseCheckResult(
            allowed=False,
            reason=f"Subscription is {sub.status}. Existing documents remain fully readable and exportable.",
            status=sub.status,
            plan_key=sub.plan_key,
            documents_used=doc_count,
            documents_limit=plan["max_documents"],
            storage_used_bytes=storage_bytes,
            storage_limit_bytes=plan["max_storage_bytes"],
        )

    if plan["max_documents"] is not None and doc_count >= plan["max_documents"]:
        return LicenseCheckResult(
            allowed=False,
            reason=f"Document limit reached ({doc_count}/{plan['max_documents']} on the {plan['label']} plan). Existing documents remain fully readable and exportable.",
            status=sub.status,
            plan_key=sub.plan_key,
            documents_used=doc_count,
            documents_limit=plan["max_documents"],
            storage_used_bytes=storage_bytes,
            storage_limit_bytes=plan["max_storage_bytes"],
        )

    if plan["max_storage_bytes"] is not None and storage_bytes >= plan["max_storage_bytes"]:
        return LicenseCheckResult(
            allowed=False,
            reason=f"Storage limit reached ({storage_bytes / 1024**3:.2f}GB/{plan['max_storage_bytes'] / 1024**3:.0f}GB on the {plan['label']} plan). Existing documents remain fully readable and exportable.",
            status=sub.status,
            plan_key=sub.plan_key,
            documents_used=doc_count,
            documents_limit=plan["max_documents"],
            storage_used_bytes=storage_bytes,
            storage_limit_bytes=plan["max_storage_bytes"],
        )

    return LicenseCheckResult(
        allowed=True,
        reason=None,
        status=sub.status,
        plan_key=sub.plan_key,
        documents_used=doc_count,
        documents_limit=plan["max_documents"],
        storage_used_bytes=storage_bytes,
        storage_limit_bytes=plan["max_storage_bytes"],
        expires_at=sub.trial_ends_at if sub.status == "trialing" else sub.current_period_end,
    )


async def get_installed_license(db: AsyncSession) -> Optional[License]:
    res = await db.execute(select(License).order_by(License.installed_at.desc()).limit(1))
    return res.scalars().first()


async def install_license(db: AsyncSession, raw_bytes: bytes, installed_by: Optional[UUID]) -> License:
    """Parses a {"payload": {...}, "signature_b64": "..."} envelope, verifies
    it, and stores it as the deployment's current license regardless of
    validity — an invalid install attempt should be visible in status/audit,
    not silently discarded."""
    try:
        envelope = json.loads(raw_bytes)
        payload = envelope["payload"]
        signature_b64 = envelope["signature_b64"]
    except (json.JSONDecodeError, KeyError, TypeError) as e:
        payload = {}
        signature_b64 = ""
        is_valid, reason = False, f"Not a valid license file: {e}"
    else:
        is_valid, reason = verify_license_signature(payload, signature_b64)
        if is_valid:
            expires_at = payload.get("expires_at")
            if expires_at and datetime.fromisoformat(expires_at.replace("Z", "+00:00")).replace(tzinfo=None) < datetime.utcnow():
                is_valid, reason = False, f"License expired on {expires_at}"

    lic = License(
        raw_payload=payload,
        signature_b64=signature_b64,
        is_valid=is_valid,
        invalid_reason=reason,
        installed_by=installed_by,
    )
    db.add(lic)
    await db.commit()
    await db.refresh(lic)
    return lic


async def check_onprem_capacity(db: AsyncSession) -> LicenseCheckResult:
    lic = await get_installed_license(db)

    if lic is None:
        return LicenseCheckResult(
            allowed=False,
            reason="No license installed. Upload a signed license file via POST /api/v1/billing/license.",
            status="blocked",
        )

    grace_deadline = lic.installed_at + timedelta(days=settings.license_grace_period_days)
    if not lic.is_valid:
        if datetime.utcnow() < grace_deadline:
            return LicenseCheckResult(
                allowed=True,
                reason=f"License invalid ({lic.invalid_reason}) — in grace period until {grace_deadline.date().isoformat()}.",
                status="grace",
            )
        return LicenseCheckResult(
            allowed=False,
            reason=f"License invalid ({lic.invalid_reason}) and grace period expired. Existing documents remain fully readable and exportable.",
            status="blocked",
        )

    expires_at_raw = lic.raw_payload.get("expires_at")
    expires_at = datetime.fromisoformat(expires_at_raw.replace("Z", "+00:00")).replace(tzinfo=None) if expires_at_raw else None
    if expires_at and datetime.utcnow() > expires_at:
        if datetime.utcnow() < expires_at + timedelta(days=settings.license_grace_period_days):
            return LicenseCheckResult(allowed=True, reason=f"License expired {expires_at.date().isoformat()} — in grace period.", status="grace", expires_at=expires_at)
        return LicenseCheckResult(
            allowed=False,
            reason=f"License expired on {expires_at.date().isoformat()} and grace period elapsed. Existing documents remain fully readable and exportable.",
            status="blocked",
            expires_at=expires_at,
        )

    return LicenseCheckResult(allowed=True, reason=None, status="active", plan_key=lic.raw_payload.get("plan_key"), expires_at=expires_at)


async def check_upload_allowed(db: AsyncSession, tenant_id: UUID) -> LicenseCheckResult:
    if not settings.license_enforcement_enabled:
        return LicenseCheckResult(allowed=True, reason=None, status="enforcement_disabled")
    if settings.deployment_mode == "on_prem":
        return await check_onprem_capacity(db)
    return await check_saas_capacity(db, tenant_id)
